/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ParkourGameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "characters"
      | "confidentialProtocolId"
      | "getAllPlayers"
      | "getLeaderboard"
      | "getLeaderboardRange"
      | "getMaxEncryptedScore"
      | "getPlayerCharacters"
      | "getPlayerCount"
      | "getPlayerScore"
      | "getTopPlayer"
      | "hasCharacter"
      | "mintCharacter"
      | "ownerTokens"
      | "playerScores"
      | "submitScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CharacterMinted"
      | "LeaderboardUpdated"
      | "ScoreSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "characters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboardRange",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxEncryptedScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerCharacters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopPlayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasCharacter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCharacter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownerTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerScores",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitScore",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "characters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboardRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxEncryptedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerCharacters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCharacter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCharacter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitScore",
    data: BytesLike
  ): Result;
}

export namespace CharacterMintedEvent {
  export type InputTuple = [owner: AddressLike, tokenId: BigNumberish];
  export type OutputTuple = [owner: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaderboardUpdatedEvent {
  export type InputTuple = [player: AddressLike, rank: BigNumberish];
  export type OutputTuple = [player: string, rank: bigint];
  export interface OutputObject {
    player: string;
    rank: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreSubmittedEvent {
  export type InputTuple = [player: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [player: string, timestamp: bigint];
  export interface OutputObject {
    player: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ParkourGame extends BaseContract {
  connect(runner?: ContractRunner | null): ParkourGame;
  waitForDeployment(): Promise<this>;

  interface: ParkourGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  characters: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean] & {
        tokenId: bigint;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getAllPlayers: TypedContractMethod<[], [string[]], "view">;

  getLeaderboard: TypedContractMethod<
    [],
    [[string[], bigint[]] & { players: string[]; timestamps: bigint[] }],
    "view"
  >;

  getLeaderboardRange: TypedContractMethod<
    [startIndex: BigNumberish, count: BigNumberish],
    [
      [string[], string[], bigint[]] & {
        players: string[];
        encryptedScores: string[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;

  getMaxEncryptedScore: TypedContractMethod<[], [string], "view">;

  getPlayerCharacters: TypedContractMethod<
    [player: AddressLike],
    [bigint[]],
    "view"
  >;

  getPlayerCount: TypedContractMethod<[], [bigint], "view">;

  getPlayerScore: TypedContractMethod<
    [player: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedScore: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getTopPlayer: TypedContractMethod<
    [],
    [[string, string] & { topPlayer: string; maxScoreHandle: string }],
    "view"
  >;

  hasCharacter: TypedContractMethod<
    [player: AddressLike],
    [[boolean, bigint] & { has: boolean; tokenId: bigint }],
    "view"
  >;

  mintCharacter: TypedContractMethod<[], [bigint], "nonpayable">;

  ownerTokens: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  playerScores: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedScore: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  submitScore: TypedContractMethod<
    [encryptedScore: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "characters"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean] & {
        tokenId: bigint;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllPlayers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<
    [],
    [[string[], bigint[]] & { players: string[]; timestamps: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaderboardRange"
  ): TypedContractMethod<
    [startIndex: BigNumberish, count: BigNumberish],
    [
      [string[], string[], bigint[]] & {
        players: string[];
        encryptedScores: string[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMaxEncryptedScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPlayerCharacters"
  ): TypedContractMethod<[player: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPlayerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerScore"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedScore: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTopPlayer"
  ): TypedContractMethod<
    [],
    [[string, string] & { topPlayer: string; maxScoreHandle: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasCharacter"
  ): TypedContractMethod<
    [player: AddressLike],
    [[boolean, bigint] & { has: boolean; tokenId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintCharacter"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "ownerTokens"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerScores"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedScore: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitScore"
  ): TypedContractMethod<
    [encryptedScore: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CharacterMinted"
  ): TypedContractEvent<
    CharacterMintedEvent.InputTuple,
    CharacterMintedEvent.OutputTuple,
    CharacterMintedEvent.OutputObject
  >;
  getEvent(
    key: "LeaderboardUpdated"
  ): TypedContractEvent<
    LeaderboardUpdatedEvent.InputTuple,
    LeaderboardUpdatedEvent.OutputTuple,
    LeaderboardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreSubmitted"
  ): TypedContractEvent<
    ScoreSubmittedEvent.InputTuple,
    ScoreSubmittedEvent.OutputTuple,
    ScoreSubmittedEvent.OutputObject
  >;

  filters: {
    "CharacterMinted(address,uint256)": TypedContractEvent<
      CharacterMintedEvent.InputTuple,
      CharacterMintedEvent.OutputTuple,
      CharacterMintedEvent.OutputObject
    >;
    CharacterMinted: TypedContractEvent<
      CharacterMintedEvent.InputTuple,
      CharacterMintedEvent.OutputTuple,
      CharacterMintedEvent.OutputObject
    >;

    "LeaderboardUpdated(address,uint256)": TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;
    LeaderboardUpdated: TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;

    "ScoreSubmitted(address,uint256)": TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
    ScoreSubmitted: TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
  };
}
